/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.SGIM;


import javafx.scene.image.Image;
import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{
    
    public static void main(String[] args) {
        launch(args);
    }
    
    
    @Override
    public void start (Stage primaryStage) throws IOException{
        
        
        
        
        
        
        Parent cofre = FXMLLoader.load(getClass().getResource("/ventanas/Cofre.fxml"));
        
        
        
        
        
        
        
        
        Scene scene = new Scene(cofre);
        primaryStage.setResizable(false);
        primaryStage.setScene(scene);
        primaryStage.getIcons().add(new Image("/imagenes/Cofre.png"));
        primaryStage.setTitle("SGIM");
        primaryStage.show();
        
        
        
    }
    


    
}
